[package]
name = "firefox-native-base16"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
notify = "6.1.1"
serde = "1.0.204"
serde_derive = "1.0.204"
serde_json = "1.0.120"
toml = "0.8.16"
